/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvatarAvatarIdRouteImport } from './routes/avatar.$avatarId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarAvatarIdRoute = AvatarAvatarIdRouteImport.update({
  id: '/avatar/$avatarId',
  path: '/avatar/$avatarId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avatar/$avatarId': typeof AvatarAvatarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avatar/$avatarId': typeof AvatarAvatarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avatar/$avatarId': typeof AvatarAvatarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/avatar/$avatarId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/avatar/$avatarId'
  id: '__root__' | '/' | '/avatar/$avatarId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvatarAvatarIdRoute: typeof AvatarAvatarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar/$avatarId': {
      id: '/avatar/$avatarId'
      path: '/avatar/$avatarId'
      fullPath: '/avatar/$avatarId'
      preLoaderRoute: typeof AvatarAvatarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvatarAvatarIdRoute: AvatarAvatarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
